// engine.js — The Mystery of Brita Svani
// Do not edit this file. All content lives in scenes.js.

const STATE = {
  currentScene: null,
  inventory: [],
  removedProps: {},
  visitedScenes: {},
  editorMode: false,
  dialogueOpen: false,
  inventoryOpen: false,
  lightboxOpen: false,
  choiceOpen: false,
  musicEnabled: true,
  musicVolume: 0.5,
  panX: 0,
  panTarget: 0,
  panScene: false,
  panKeys: { left: false, right: false },
  // Dialogue sequence state
  seqLines: [],
  seqIndex: 0,
  seqOnComplete: null,
};

const PAN_SPEED = 6;
const PAN_LERP  = 0.10;

// ─── AUDIO ───────────────────────────────────────────────────────────────────

const bgMusic = new Audio("assets/audio/score.mp3");
bgMusic.loop = true;
bgMusic.volume = STATE.musicVolume;

function startMusic() { if (STATE.musicEnabled) bgMusic.play().catch(() => {}); }
function setMusicEnabled(val) {
  STATE.musicEnabled = val;
  val ? bgMusic.play().catch(() => {}) : bgMusic.pause();
  updateSettingsUI();
}
function setMusicVolume(val) {
  STATE.musicVolume = val;
  bgMusic.volume = val;
  updateSettingsUI();
}

// ─── INIT ────────────────────────────────────────────────────────────────────

function startGame() {
  document.getElementById("title-screen").style.display = "none";
  document.getElementById("settings-screen").style.display = "none";
  document.getElementById("top-bar").style.display = "flex";
  document.getElementById("inventory-btn").style.display = "flex";
  loadScene("exterior");
  fadeIn();
  startMusic();
  requestAnimationFrame(panLoop);
}

function resumeGame() {
  const saved = localStorage.getItem('brita_save');
  if (saved) {
    try {
      const data = JSON.parse(saved);
      document.getElementById("title-screen").style.display = "none";
      document.getElementById("settings-screen").style.display = "none";
      document.getElementById("top-bar").style.display = "flex";
      document.getElementById("inventory-btn").style.display = "flex";
      if (data.inventory) STATE.inventory = data.inventory;
      if (data.removedProps) STATE.removedProps = data.removedProps;
      if (data.visitedScenes) STATE.visitedScenes = data.visitedScenes;
      loadScene(data.scene || "exterior");
      fadeIn();
      startMusic();
      requestAnimationFrame(panLoop);
    } catch(e) { startGame(); }
  } else {
    showTitleMessage("No saved game found — starting new game...");
    setTimeout(startGame, 1800);
  }
}

function openSettings() { document.getElementById("settings-screen").style.display = "flex"; }
function closeSettings() { document.getElementById("settings-screen").style.display = "none"; }

function showTitleMessage(msg) {
  const el = document.createElement("div");
  el.textContent = msg;
  el.style.cssText = "position:absolute;bottom:10%;left:20%;font-size:14px;font-style:italic;color:rgba(60,40,20,0.75);font-family:Georgia,serif;pointer-events:none;z-index:300;letter-spacing:0.06em;";
  document.getElementById("title-screen").appendChild(el);
  setTimeout(() => el.remove(), 2000);
}

function loadScene(sceneId, onReady) {
  const scene = SCENES[sceneId];
  if (!scene) { console.error("Scene not found:", sceneId); return; }

  const firstVisit = !STATE.visitedScenes[sceneId];
  STATE.currentScene = scene;
  STATE.visitedScenes[sceneId] = true;

  const bg = document.getElementById("background");
  STATE.panScene = scene.type === "pan";
  const prevSrc = bg.src;

  const finishLoad = () => {
    if (STATE.panScene) {
      // Recalculate using real image dimensions AFTER load
      const maxPan = getMaxPan();
      const startFrac = scene.panStart !== undefined ? scene.panStart : 0;
      STATE.panX = startFrac * maxPan;
      STATE.panTarget = STATE.panX;
      renderHotspots(scene); // Must run after load so getScaledImageWidth() is accurate
      applyPan();
    }
    if (onReady) onReady();
  };

  if (STATE.panScene) {
    bg.style.width = "auto";
    bg.style.height = "100%";
    bg.style.objectFit = "unset";
    bg.style.maxWidth = "none";
    bg.style.transform = "";
    bg.onload = finishLoad;
  } else {
    bg.style.width = "100%";
    bg.style.height = "100%";
    bg.style.objectFit = "cover";
    bg.style.maxWidth = "";
    bg.style.transform = "";
    bg.onload = finishLoad;
    STATE.panX = 0;
    STATE.panTarget = 0;
    // Reset layers
    const hl = document.getElementById("hotspot-layer");
    const pl = document.getElementById("prop-layer");
    hl.style.transform = ""; hl.style.width = "100%"; hl.style.height = "100%"; hl.style.left = "0";
    pl.style.transform = ""; pl.style.width = "100%"; pl.style.height = "100%";
    renderHotspots(scene);
  }

  bg.src = scene.background;
  // If the new background is the same image already loaded (e.g. re-entering
  // a scene that shares an image), the browser won't fire a fresh load event.
  if (bg.src === prevSrc && bg.complete && bg.naturalWidth > 0) finishLoad();
  document.getElementById("scene-label").textContent = scene.name;

  // Pan hint
  const panHint = document.getElementById("pan-hint");
  if (panHint) {
    if (STATE.panScene && scene.showPanHint && firstVisit) {
      panHint.style.display = "flex"; panHint.style.opacity = "1";
      setTimeout(() => {
        panHint.style.transition = "opacity 0.8s ease"; panHint.style.opacity = "0";
        setTimeout(() => { panHint.style.display = "none"; panHint.style.transition = ""; panHint.style.opacity = "1"; }, 800);
      }, 3000);
    } else {
      panHint.style.display = "none";
    }
  }

  closeInventory(); closeLightbox(); closeChoice();
  renderProps(scene);
  renderInventory();

  // onEnter trigger
  if (scene.onEnter && firstVisit) {
    setTimeout(() => {
      if (scene.onEnter.type === "dialogue") {
        showDialogue(scene.onEnter.speaker, scene.onEnter.text);
      } else if (scene.onEnter.type === "dialogue_sequence_auto") {
        startSequence(scene.onEnter.lines, scene.onEnter.onComplete);
      }
    }, 600);
  } else if (scene.onEnter && scene.onEnter.type === "dialogue_sequence_auto" && !firstVisit) {
    // On repeat visits to ending scene, just open choice if not already done
  }

  // Auto-save
  setTimeout(() => {
    localStorage.setItem('brita_save', JSON.stringify({
      scene: sceneId,
      inventory: STATE.inventory,
      removedProps: STATE.removedProps,
      visitedScenes: STATE.visitedScenes
    }));
  }, 200);
}

// ─── PAN ─────────────────────────────────────────────────────────────────────

function getScaledImageWidth() {
  const bg = document.getElementById("background");
  // Use actual loaded dimensions — no hardcoded fallback
  // If image not loaded yet, return viewport width as safe default
  if (!bg.naturalWidth) return window.innerWidth;
  return bg.naturalWidth * (window.innerHeight / bg.naturalHeight);
}

function getMaxPan() { return Math.max(0, getScaledImageWidth() - window.innerWidth); }

function applyPan() {
  if (!STATE.panScene) return;
  const tx = -Math.round(STATE.panX);
  const bg = document.getElementById("background");
  const pl = document.getElementById("prop-layer");
  const hl = document.getElementById("hotspot-layer");
  bg.style.transform = `translateX(${tx}px)`;
  pl.style.transform = `translateX(${tx}px)`;
  hl.style.transform = `translateX(${tx}px)`;
}

function panLoop() {
  requestAnimationFrame(panLoop);
  if (!STATE.panScene) return;
  if (STATE.panKeys.left)  STATE.panTarget = Math.max(0, STATE.panTarget - PAN_SPEED);
  if (STATE.panKeys.right) STATE.panTarget = Math.min(getMaxPan(), STATE.panTarget + PAN_SPEED);
  STATE.panX += (STATE.panTarget - STATE.panX) * PAN_LERP;
  applyPan();
}

// ─── PROPS ───────────────────────────────────────────────────────────────────

function getCoverRect() {
  const vw = window.innerWidth, vh = window.innerHeight;
  const bg = document.getElementById("background");
  if (STATE.panScene) {
    const scale = vh / (bg.naturalHeight || vh);
    return { offsetX: 0, offsetY: 0, renderedW: (bg.naturalWidth || vw) * scale, renderedH: vh };
  }
  const nw = bg.naturalWidth || 1920, nh = bg.naturalHeight || 1080;
  const scale = Math.max(vw / nw, vh / nh);
  const rW = nw * scale, rH = nh * scale;
  return { offsetX: (rW - vw) / 2, offsetY: (rH - vh) / 2, renderedW: rW, renderedH: rH };
}

function positionProp(el, prop) {
  const { offsetX, offsetY, renderedW, renderedH } = getCoverRect();
  el.style.left   = ((prop.x / 100) * renderedW - offsetX) + "px";
  el.style.top    = ((prop.y / 100) * renderedH - offsetY) + "px";
  el.style.width  = ((prop.width  / 100) * renderedW) + "px";
  el.style.height = ((prop.height / 100) * renderedH) + "px";
}

function renderProps(scene) {
  const layer = document.getElementById("prop-layer");
  layer.innerHTML = "";
  if (!scene.props) return;
  const removed = STATE.removedProps[scene.id] || {};
  scene.props.forEach(prop => {
    if (removed[prop.id]) return;
    const el = document.createElement("img");
    el.src = prop.image + "?v=1";
    el.id = "prop-" + prop.id;
    el.style.cssText = "position:absolute;pointer-events:none;";
    positionProp(el, prop);
    el.onload = () => positionProp(el, prop);
    layer.appendChild(el);
  });
}

window.addEventListener("resize", () => {
  if (!STATE.currentScene) return;
  renderHotspots(STATE.currentScene);
  const removed = STATE.removedProps[STATE.currentScene.id] || {};
  (STATE.currentScene.props || []).forEach(prop => {
    if (removed[prop.id]) return;
    const el = document.getElementById("prop-" + prop.id);
    if (el) positionProp(el, prop);
  });
});

function removeProp(sceneId, propId) {
  if (!STATE.removedProps[sceneId]) STATE.removedProps[sceneId] = {};
  STATE.removedProps[sceneId][propId] = true;
  const el = document.getElementById("prop-" + propId);
  if (el) { el.style.transition = "opacity 0.35s"; el.style.opacity = "0"; setTimeout(() => el.remove(), 360); }
}

// ─── HOTSPOTS ────────────────────────────────────────────────────────────────

function renderHotspots(scene) {
  const layer = document.getElementById("hotspot-layer");
  layer.innerHTML = "";
  const isPan = scene.type === "pan";
  const vh = window.innerHeight;

  if (isPan) {
    const scaledW = getScaledImageWidth();
    layer.style.position = "absolute"; layer.style.top = "0"; layer.style.left = "0";
    layer.style.width = scaledW + "px"; layer.style.height = vh + "px";
  } else {
    layer.style.width = "100%"; layer.style.height = "100%";
  }

  scene.hotspots.forEach(hs => {
    // Hide hotspots that require an item the player doesn't have
    // (for second-visit-only items like Edward's note)
    if (hs.requiresItem && !STATE.inventory.find(i => i.id === hs.requiresItem)) return;

    const el = document.createElement("div");
    el.className = "hotspot" + (STATE.editorMode ? " debug" : "");

    if (isPan) {
      const scaledW = getScaledImageWidth();
      el.style.position = "absolute";
      el.style.left   = (hs.x / 100 * scaledW) + "px";
      el.style.top    = (hs.y / 100 * vh) + "px";
      el.style.width  = (hs.width  / 100 * scaledW) + "px";
      el.style.height = (hs.height / 100 * vh) + "px";
    } else {
      el.style.cssText = `left:${hs.x}%;top:${hs.y}%;width:${hs.width}%;height:${hs.height}%`;
    }

    el.dataset.id = hs.id;
    const label = document.createElement("div");
    label.className = "hotspot-label";
    label.textContent = hs.label;
    el.appendChild(label);
    el.addEventListener("click", () => { if (!STATE.editorMode) triggerHotspot(hs); });
    layer.appendChild(el);
  });
}

// ─── TRIGGER ─────────────────────────────────────────────────────────────────

function triggerHotspot(hs) {
  const action = hs.action;
  if (!action) return;

  if (action.type === "dialogue") {
    showDialogue(action.speaker, action.text);

  } else if (action.type === "dialogue_sequence") {
    startSequence(action.lines, action.onComplete);

  } else if (action.type === "pickup") {
    const alreadyHave = STATE.inventory.find(i => i.id === action.item.id);
    if (!alreadyHave) {
      STATE.inventory.push(action.item);
      renderInventory();
      showPickupNotification(action.item.label);
      if (action.removesProp) removeProp(STATE.currentScene.id, action.removesProp);
      const hotspotEl = document.querySelector(`[data-id="${hs.id}"]`);
      if (hotspotEl) hotspotEl.style.display = "none";
      if (action.showLightbox) {
        openLightbox(action.showLightbox, action.text);
      } else {
        showDialogue(action.speaker, action.text);
      }
    } else {
      showDialogue(action.speaker, action.alreadyTaken || "I already have that.");
    }

  } else if (action.type === "scene") {
    closeInventory(); closeLightbox();
    fadeOut(() => { loadScene(action.target, fadeIn); });

  } else if (action.type === "lightbox") {
    openLightbox(action.image, action.caption);

  } else if (action.type === "conditional") {
    const hasItem = action.requiresItem ? STATE.inventory.find(i => i.id === action.requiresItem) : true;
    if (hasItem) {
      if (action.showLightboxOnSuccess) {
        openLightbox(action.showLightboxOnSuccess, action.textSuccess);
        if (action.then) setTimeout(() => handleThen(action.then), 800);
      } else if (action.textSuccess) {
        showDialogue(action.speaker, action.textSuccess);
        if (action.then) setTimeout(() => handleThen(action.then), 1600);
      }
    } else {
      // textFail_sequence allows a sequence to play when condition NOT met
      if (action.textFail_sequence) {
        const seq = action.textFail_sequence;
        if (seq.type === "dialogue_sequence") {
          startSequence(seq.lines, seq.onComplete);
        } else if (seq.type === "photograph_flip") {
          openPhotographFlip(seq.imageFront, seq.imageBack, seq.captionFront, seq.captionBack, seq.then);
        }
      } else if (action.textFail) {
        showDialogue(action.speaker, action.textFail);
      }
    }

  } else if (action.type === "choice") {
    openChoice();
  } else if (action.type === "photograph_flip") {
    // Show front of photo, clicking it flips to back (coordinates)
    openPhotographFlip(action.imageFront, action.imageBack, action.captionFront, action.captionBack, action.then);
  }
}

function handleThen(then) {
  if (then.type === "scene") {
    fadeOut(() => { loadScene(then.target, fadeIn); });
  } else if (then.type === "pickup") {
    if (!STATE.inventory.find(i => i.id === then.item.id)) {
      STATE.inventory.push(then.item);
      renderInventory();
      showPickupNotification(then.item.label);
      showDialogue(then.speaker, then.text);
    }
  } else if (then.type === "endcard") {
    showEndCard(then.branch);
  }
}

// ─── DIALOGUE SEQUENCE ───────────────────────────────────────────────────────

function startSequence(lines, onComplete) {
  STATE.seqLines = lines;
  STATE.seqIndex = 0;
  STATE.seqOnComplete = onComplete || null;
  closeInventory();
  showSeqLine();
}

function showSeqLine() {
  const line = STATE.seqLines[STATE.seqIndex];
  if (!line) { endSequence(); return; }
  showDialogue(line.speaker, line.text);
  STATE.dialogueOpen = true;
  // Override click to advance sequence
  const box = document.getElementById("dialogue-box");
  box.onclick = (e) => { e.stopPropagation(); advanceSequence(); };
}

function advanceSequence() {
  STATE.seqIndex++;
  if (STATE.seqIndex >= STATE.seqLines.length) {
    endSequence();
  } else {
    showSeqLine();
  }
}

function endSequence() {
  closeDialogue();
  document.getElementById("dialogue-box").onclick = (e) => { e.stopPropagation(); closeDialogue(); };
  if (STATE.seqOnComplete) {
    const oc = STATE.seqOnComplete;
    STATE.seqOnComplete = null;
    if (oc.type === "pickup") {
      if (!STATE.inventory.find(i => i.id === oc.item.id)) {
        STATE.inventory.push(oc.item);
        renderInventory();
        showPickupNotification(oc.item.label);
        showDialogue(oc.speaker, oc.text);
        document.getElementById("dialogue-box").onclick = closeDialogue;
      }
    } else if (oc.type === "choice") {
      setTimeout(openChoice, 400);
    } else if (oc.type === "endcard") {
      showEndCard(oc.branch);
    } else {
      handleThen(oc);
    }
  }
}

// ─── CHOICE SCREEN ───────────────────────────────────────────────────────────

// ─── PHOTOGRAPH FLIP ─────────────────────────────────────────────────────────
// Two-sided photograph: click front → shows back (coordinates)

let flipState = { active: false, imageFront: null, imageBack: null, showingBack: false, pendingThen: null };

function openPhotographFlip(imageFront, imageBack, captionFront, captionBack, then) {
  flipState = { active: true, imageFront, imageBack, showingBack: false, captionFront, captionBack, pendingThen: then || null };
  openLightbox(imageFront, captionFront + " — click the edge to turn over");
  // Override lightbox click to flip rather than close
  document.getElementById("lightbox").onclick = flipPhotograph;
}

function flipPhotograph(e) {
  e.stopPropagation();
  if (!flipState.active) return;
  if (!flipState.showingBack) {
    flipState.showingBack = true;
    document.getElementById("lightbox-img").src = flipState.imageBack;
    const hint = document.getElementById("lightbox-hint");
    if (hint) hint.textContent = flipState.captionBack + " — click to close";
    // Next click closes and triggers then
    document.getElementById("lightbox").onclick = (ev) => {
      ev.stopPropagation();
      flipState.active = false;
      document.getElementById("lightbox").onclick = () => closeLightbox();
      closeLightbox();
      if (flipState.pendingThen) {
        setTimeout(() => handleThen(flipState.pendingThen), 400);
        flipState.pendingThen = null;
      }
    };
  }
}

function openChoice() {
  STATE.choiceOpen = true;
  closeDialogue();
  document.getElementById("choice-screen").style.display = "flex";
}

function closeChoice() {
  STATE.choiceOpen = false;
  const cs = document.getElementById("choice-screen");
  if (cs) cs.style.display = "none";
}

function makeChoice(branch) {
  closeChoice();
  fadeOut(() => { loadScene("ending_" + branch, fadeIn); });
}

// ─── END CARD ────────────────────────────────────────────────────────────────

const END_CARDS = {
  a: [
    "She came back on a Tuesday.",
    "The theatre gave her a standing ovation.",
    "She didn't acknowledge it.",
    "",
    "Hector was not at the bar when I returned.",
    "",
    "The cat was never found."
  ],
  b: [
    "I told Edvard I had no leads.",
    "He didn't believe me.",
    "",
    "Somewhere past the city lights,",
    "someone is listening to old opera",
    "and watching the view.",
    "",
    "I closed the file."
  ]
};

function showEndCard(branch) {
  const lines = END_CARDS[branch] || [];
  const ec = document.getElementById("end-card");
  const et = document.getElementById("end-card-text");
  et.innerHTML = lines.map(l => l ? `<p>${l}</p>` : "<br>").join("");
  ec.style.display = "flex";
  ec.style.opacity = "0";
  setTimeout(() => { ec.style.transition = "opacity 1.5s ease"; ec.style.opacity = "1"; }, 100);
}

function closeEndCard() {
  const ec = document.getElementById("end-card");
  ec.style.transition = "opacity 0.8s ease";
  ec.style.opacity = "0";
  setTimeout(() => {
    ec.style.display = "none";
    goToMainMenu();
  }, 800);
}

// ─── LIGHTBOX ────────────────────────────────────────────────────────────────

function openLightbox(imageSrc, caption) {
  STATE.lightboxOpen = true;
  closeDialogue(); closeInventory();
  const lb = document.getElementById("lightbox");
  document.getElementById("lightbox-img").src = imageSrc;
  const hint = document.getElementById("lightbox-hint");
  if (hint && caption) hint.textContent = caption;
  else if (hint) hint.textContent = "esc to close";
  lb.style.display = "flex";
  requestAnimationFrame(() => lb.classList.add("open"));
}

function closeLightbox() {
  STATE.lightboxOpen = false;
  const lb = document.getElementById("lightbox");
  lb.classList.remove("open");
  setTimeout(() => { lb.style.display = "none"; }, 280);
}

// ─── DIALOGUE ────────────────────────────────────────────────────────────────

function showDialogue(speaker, text) {
  STATE.dialogueOpen = true;
  closeInventory();
  document.getElementById("dialogue-speaker").textContent = speaker || "";
  document.getElementById("dialogue-text").textContent = text;
  document.getElementById("dialogue-box").style.display = "block";
  document.getElementById("dialogue-box").onclick = closeDialogue;
}

function closeDialogue() {
  STATE.dialogueOpen = false;
  document.getElementById("dialogue-box").style.display = "none";
}

// ─── INVENTORY ───────────────────────────────────────────────────────────────

const ITEM_ICONS = {
  mystery_bottle: `<svg viewBox="0 0 22 22" fill="none"><path d="M8 2h6v3l2 3v10a1.5 1.5 0 01-1.5 1.5h-5A1.5 1.5 0 018 18V8l2-3z" stroke="rgba(232,218,185,0.9)" stroke-width="1.3" fill="rgba(232,218,185,0.08)"/><line x1="7.5" y1="11" x2="14.5" y2="11" stroke="rgba(232,218,185,0.5)" stroke-width="1"/></svg>`,
  note_h: `<svg viewBox="0 0 22 22" fill="none"><rect x="3" y="5" width="16" height="12" rx="1" stroke="rgba(232,218,185,0.9)" stroke-width="1.3" fill="rgba(232,218,185,0.08)"/><line x1="6" y1="9" x2="16" y2="9" stroke="rgba(232,218,185,0.5)" stroke-width="1"/><line x1="6" y1="12" x2="13" y2="12" stroke="rgba(232,218,185,0.5)" stroke-width="1"/></svg>`,
  theatre_key: `<svg viewBox="0 0 22 22" fill="none"><circle cx="7" cy="9" r="4" stroke="rgba(232,218,185,0.9)" stroke-width="1.3" fill="none"/><circle cx="7" cy="9" r="1.5" stroke="rgba(232,218,185,0.5)" stroke-width="1" fill="none"/><line x1="10.5" y1="11.5" x2="18" y2="19" stroke="rgba(232,218,185,0.9)" stroke-width="1.5" stroke-linecap="round"/><line x1="15" y1="17" x2="15" y2="19.5" stroke="rgba(232,218,185,0.6)" stroke-width="1.3" stroke-linecap="round"/></svg>`,
  box_key: `<svg viewBox="0 0 22 22" fill="none"><circle cx="6" cy="8" r="3" stroke="rgba(232,218,185,0.9)" stroke-width="1.3" fill="none"/><circle cx="6" cy="8" r="1.2" stroke="rgba(232,218,185,0.5)" stroke-width="1" fill="none"/><line x1="8.5" y1="10" x2="17" y2="18" stroke="rgba(232,218,185,0.9)" stroke-width="1.4" stroke-linecap="round"/></svg>`,
  photograph: `<svg viewBox="0 0 22 22" fill="none"><rect x="3" y="4" width="16" height="14" rx="1" stroke="rgba(232,218,185,0.9)" stroke-width="1.3" fill="rgba(232,218,185,0.06)"/><circle cx="11" cy="10" r="3" stroke="rgba(232,218,185,0.45)" stroke-width="1" fill="none"/><line x1="3" y1="14" x2="19" y2="14" stroke="rgba(30,20,10,0.2)" stroke-width="1"/></svg>`,
  coordinates: `<svg viewBox="0 0 22 22" fill="none"><rect x="4" y="3" width="14" height="16" rx="1" stroke="rgba(232,218,185,0.9)" stroke-width="1.3" fill="rgba(232,218,185,0.06)"/><line x1="7" y1="7" x2="15" y2="7" stroke="rgba(232,218,185,0.6)" stroke-width="1"/><line x1="7" y1="10" x2="15" y2="10" stroke="rgba(232,218,185,0.6)" stroke-width="1"/><line x1="7" y1="13" x2="12" y2="13" stroke="rgba(232,218,185,0.6)" stroke-width="1"/></svg>`,
  default: `<svg viewBox="0 0 22 22" fill="none"><rect x="4" y="4" width="14" height="14" rx="2" stroke="rgba(232,218,185,0.8)" stroke-width="1.3" fill="rgba(232,218,185,0.05)"/></svg>`
};

function renderItemIcon(item) { return ITEM_ICONS[item.id] || ITEM_ICONS["default"]; }

function renderInventory() {
  const grid = document.getElementById("inventory-grid");
  const countEl = document.getElementById("inv-count");
  grid.innerHTML = "";
  const totalSlots = Math.max(10, Math.ceil((STATE.inventory.length + 1) / 5) * 5);
  for (let i = 0; i < totalSlots; i++) {
    const item = STATE.inventory[i];
    const slot = document.createElement("div");
    slot.className = "inv-slot" + (item ? " filled" : "");
    if (item) {
      slot.innerHTML = renderItemIcon(item);
      const tip = document.createElement("div");
      tip.className = "inv-tooltip";
      tip.textContent = item.label;
      slot.appendChild(tip);
    }
    grid.appendChild(slot);
  }
  if (STATE.inventory.length > 0) {
    countEl.textContent = STATE.inventory.length;
    countEl.style.display = "flex";
  } else { countEl.style.display = "none"; }
}

function toggleInventory() { STATE.inventoryOpen ? closeInventory() : openInventory(); }

function openInventory() {
  STATE.inventoryOpen = true;
  const panel = document.getElementById("inventory-panel");
  panel.style.display = "block";
  requestAnimationFrame(() => panel.classList.add("open"));
}

function closeInventory() {
  STATE.inventoryOpen = false;
  const panel = document.getElementById("inventory-panel");
  panel.classList.remove("open");
  setTimeout(() => { if (!STATE.inventoryOpen) panel.style.display = "none"; }, 240);
}

function showPickupNotification(label) {
  const n = document.createElement("div");
  n.textContent = "+" + label;
  n.style.cssText = "position:absolute;bottom:90px;right:80px;font-size:18px;letter-spacing:0.04em;color:rgba(30,20,10,0.85);font-family:'Caveat',cursive;pointer-events:none;z-index:400;opacity:1;transition:opacity 0.5s,transform 0.5s;transform:translateY(0);background:rgba(232,222,200,0.92);padding:6px 16px;box-shadow:2px 3px 0 rgba(0,0,0,0.2);";
  document.getElementById("game-container").appendChild(n);
  requestAnimationFrame(() => {
    setTimeout(() => { n.style.opacity="0"; n.style.transform="translateY(-16px)"; setTimeout(() => n.remove(), 500); }, 1400);
  });
}

// ─── TRANSITIONS ─────────────────────────────────────────────────────────────

function fadeOut(cb) {
  const f = document.getElementById("fade");
  f.style.opacity = "1";
  setTimeout(() => { if (cb) cb(); }, 700);
}
function fadeIn() {
  const f = document.getElementById("fade");
  setTimeout(() => { f.style.opacity = "0"; }, 60);
}

// ─── TOP BAR ─────────────────────────────────────────────────────────────────

function goToMainMenu() {
  closeSettings(); closeDialogue(); closeInventory(); closeLightbox(); closeChoice();
  fadeOut(() => {
    document.getElementById("title-screen").style.display = "flex";
    document.getElementById("top-bar").style.display = "none";
    document.getElementById("inventory-btn").style.display = "none";
    document.getElementById("hotspot-layer").innerHTML = "";
    document.getElementById("prop-layer").innerHTML = "";
    document.getElementById("scene-label").textContent = "";
    const ec = document.getElementById("end-card");
    if (ec) { ec.style.display = "none"; ec.style.opacity = "0"; }
    bgMusic.pause(); bgMusic.currentTime = 0;
    STATE.panScene = false;
    fadeIn();
  });
}

let settingsOpen = false;
function toggleSettingsPanel() {
  settingsOpen = !settingsOpen;
  document.getElementById("settings-panel").style.display = settingsOpen ? "block" : "none";
}
function updateSettingsUI() {
  ["music-toggle-btn","music-toggle-btn-ingame"].forEach(id => {
    const btn = document.getElementById(id);
    if (btn) btn.textContent = STATE.musicEnabled ? "on" : "off";
  });
  ["volume-slider","volume-slider-ingame"].forEach(id => {
    const sl = document.getElementById(id);
    if (sl) sl.value = Math.round(STATE.musicVolume * 100);
  });
  ["volume-readout","volume-readout-ingame"].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.textContent = Math.round(STATE.musicVolume * 100) + "%";
  });
}

// ─── EDITOR ──────────────────────────────────────────────────────────────────

const editorCanvas = document.getElementById("drag-canvas");
const editorCtx = editorCanvas.getContext("2d");
let drag = { active: false, x0: 0, y0: 0, x1: 0, y1: 0 };

function toggleEditor() {
  STATE.editorMode = !STATE.editorMode;
  const badge = document.getElementById("editor-badge");
  const panel = document.getElementById("editor-panel");
  if (STATE.editorMode) {
    badge.style.display = "block"; panel.style.display = "block";
    editorCanvas.style.display = "block"; editorCanvas.style.pointerEvents = "all";
    resizeEditorCanvas();
  } else {
    badge.style.display = "none"; panel.style.display = "none";
    editorCanvas.style.display = "none"; editorCanvas.style.pointerEvents = "none";
    editorCtx.clearRect(0, 0, editorCanvas.width, editorCanvas.height);
  }
  if (STATE.currentScene) renderHotspots(STATE.currentScene);
}

function resizeEditorCanvas() {
  const gc = document.getElementById("game-container");
  editorCanvas.width = gc.offsetWidth;
  editorCanvas.height = gc.offsetHeight;
}

editorCanvas.addEventListener("mousedown", e => {
  if (!STATE.editorMode) return;
  resizeEditorCanvas();
  const r = editorCanvas.getBoundingClientRect();
  drag = { active:true, x0:e.clientX-r.left, y0:e.clientY-r.top, x1:e.clientX-r.left, y1:e.clientY-r.top };
});
editorCanvas.addEventListener("mousemove", e => {
  if (!STATE.editorMode || !drag.active) return;
  const r = editorCanvas.getBoundingClientRect();
  drag.x1=e.clientX-r.left; drag.y1=e.clientY-r.top; drawEditorRect();
});
editorCanvas.addEventListener("mouseup", e => {
  if (!STATE.editorMode || !drag.active) return;
  drag.active=false;
  const r = editorCanvas.getBoundingClientRect();
  drag.x1=e.clientX-r.left; drag.y1=e.clientY-r.top; drawEditorRect(); outputEditorCoords();
});

function drawEditorRect() {
  editorCtx.clearRect(0,0,editorCanvas.width,editorCanvas.height);
  const x=Math.min(drag.x0,drag.x1), y=Math.min(drag.y0,drag.y1);
  const w=Math.abs(drag.x1-drag.x0), h=Math.abs(drag.y1-drag.y0);
  editorCtx.strokeStyle="rgba(255,200,80,0.9)"; editorCtx.lineWidth=2;
  editorCtx.setLineDash([6,3]); editorCtx.strokeRect(x,y,w,h);
  editorCtx.fillStyle="rgba(255,200,80,0.07)"; editorCtx.fillRect(x,y,w,h);
}

function outputEditorCoords() {
  const isPan = STATE.panScene;
  const W = isPan ? getScaledImageWidth() : editorCanvas.width;
  const H = editorCanvas.height;
  let x0=Math.min(drag.x0,drag.x1), x1=Math.max(drag.x0,drag.x1);
  if (isPan) { x0+=STATE.panX; x1+=STATE.panX; }
  const x=Math.round(x0/W*100), y=Math.round(Math.min(drag.y0,drag.y1)/H*100);
  const w=Math.round((x1-x0)/W*100), h=Math.round(Math.abs(drag.y1-drag.y0)/H*100);
  document.getElementById("editor-coords").innerHTML=`x: ${x}%&nbsp;&nbsp;y: ${y}%<br>width: ${w}%&nbsp;&nbsp;height: ${h}%`;
  document.getElementById("editor-json").textContent=`{\n  "id": "hotspot_name",\n  "label": "What is it?",\n  "x": ${x}, "y": ${y},\n  "width": ${w}, "height": ${h},\n  "action": {\n    "type": "dialogue",\n    "speaker": "You",\n    "text": "Describe what you see."\n  }\n}`;
}

// ─── INPUT ───────────────────────────────────────────────────────────────────

document.addEventListener("keydown", e => {
  if (e.key === "ArrowLeft")  { STATE.panKeys.left  = true; if (STATE.panScene) e.preventDefault(); }
  if (e.key === "ArrowRight") { STATE.panKeys.right = true; if (STATE.panScene) e.preventDefault(); }
  if (e.key === "e" || e.key === "E") toggleEditor();
  if (e.key === "Escape") { closeDialogue(); closeSettings(); closeInventory(); closeLightbox(); closeChoice(); }
  if (e.key === "i" || e.key === "I") toggleInventory();
});
document.addEventListener("keyup", e => {
  if (e.key === "ArrowLeft")  STATE.panKeys.left  = false;
  if (e.key === "ArrowRight") STATE.panKeys.right = false;
});

document.addEventListener("mousemove", e => {
  const c = document.getElementById("custom-cursor");
  if (c) { c.style.left = e.clientX+"px"; c.style.top = e.clientY+"px"; }
});

document.addEventListener("click", e => {
  const sp = document.getElementById("settings-panel");
  const sb = document.getElementById("settings-btn");
  if (settingsOpen && sp && !sp.contains(e.target) && !sb.contains(e.target)) {
    settingsOpen = false; sp.style.display = "none";
  }
  const ip = document.getElementById("inventory-panel");
  const ib = document.getElementById("inventory-btn");
  if (STATE.inventoryOpen && ip && !ip.contains(e.target) && !ib.contains(e.target)) closeInventory();
});

// ─── BOOT ────────────────────────────────────────────────────────────────────

renderInventory();
updateSettingsUI();
